### ISSUE TITLE
Renaming of User Profiles

### ISSUE THREAD

**Issue by TIPSOM-Ninja** [TIPSOM-Ninja/Tipsom-web#13]
Updated User Profile names:

1.     Tip Process TO **TIP and SOM Process (Interception)**
2.     Investigation (Unchanged)
3.     Prosecution  (Unchanged)
4.     Assistance TO **Protection/Assistance**

**Comment by james1mumo** [comment]
![image](https://github.com/user-attachments/assets/6eb271a6-55ac-4b31-b75b-054f03cdda6e)
