### ISSUE TITLE
Mandatory fields for TiP and SoM data entry (Mobile App): VICTIM PROFILE

### ISSUE THREAD

**Issue by TIPSOM-Ninja** [TIPSOM-Ninja/Tipsom-web#5]
Mandatory fields for TiP and SoM data entry (Mobile App): VICTIM PROFILE
1. Initials
2. DOB
3. Sex
4. Race
5. Languages
6. Email address
7. Citizenship
8. Interview date
9. Interview country
10. Interview location

**Comment by james1mumo** [comment]
![image](https://github.com/user-attachments/assets/f88bdbf0-a315-4b1f-9de9-ad1638dcb0ab)
