### ISSUE TITLE
Dashboard: update metrics display (Web App)

### ISSUE THREAD

**Issue by TIPSOM-Ninja** [TIPSOM-Ninja/Tipsom-web#6]
Update Dashboard items:
1.  Victim Demographics
2. Suspect Demographics
3. Suspect Prosecution and Conviction

**Comment by james1mumo** [comment]
![image](https://github.com/user-attachments/assets/6f40095f-938e-4a69-b4f3-38c1f2110310)
![image](https://github.com/user-attachments/assets/6d95d008-6ef8-4020-88f5-aee362db346c)
